### ISSUE TITLE
Edit README.md

### ISSUE THREAD

**Issue by Rahul-Vijay** [Rahul-Vijay/C_plus_plus_Algos#10]
- Make a list of all algorithms added

- Link these algorithms to their respective files

For example - 
[Bubble Sort](https://github.com/Rahul-Vijay/C_plus_plus_Algos/blob/master/algos/BubbleSort.cpp)

**Comment by marimendes** [comment]
I can to that

**Comment by Rahul-Vijay** [comment]
please by all means :) @sahilgenius1
