### ISSUE TITLE
Refactoring of folders and files

### ISSUE THREAD

**Issue by Rahul-Vijay** [Rahul-Vijay/C_plus_plus_Algos#42]
- Follow a specified naming convention to rename existing files

- Rearrange/Make new folders that would hold in their respective algorithms
example -
`Sorting/` will contain Sorting Algorithms
`Search/` will contain Searching Algorithms

Before you make a PR, comment on how you would do it.

**Comment by srinath9721** [comment]
Can I work on this?

**Comment by Rahul-Vijay** [comment]
Sure @srinath9721, make sure all the files have a consistent naming convention like - BubbleSort.cpp, as in the starting letter of each word is capitalized followed by the extension. All the folders must contain their respective algorithms only.
